#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bittrex.Resource", IsApplication=true)]

namespace Bittrex
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int APIKey = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int SecretKey = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int Text = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Text1 = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int amountToPurchase = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int btcBalance = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int buyOrderbutton = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int buyOrders_listView = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int buyPrice = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int buyText = 2131165196;
			
			// aapt resource value: 0x7f07001d
			public const int confirmAmount = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int confirmPrice = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int confirmTotal = 2131165215;
			
			// aapt resource value: 0x7f070000
			public const int currencyFragmentContainer = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int fragmentContainer = 2131165210;
			
			// aapt resource value: 0x7f070011
			public const int lastPrice = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int lastText = 2131165200;
			
			// aapt resource value: 0x7f07001c
			public const int listView = 2131165212;
			
			// aapt resource value: 0x7f070018
			public const int login = 2131165208;
			
			// aapt resource value: 0x7f07002b
			public const int menu_preferences = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int menu_refresh = 2131165228;
			
			// aapt resource value: 0x7f070008
			public const int priceToPurchase = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int quantity = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int rate = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int searchView = 2131165211;
			
			// aapt resource value: 0x7f070003
			public const int selectedCurrencyBalance = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int selectedCurrencyBalanceAvailableText = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int sellOrderbutton = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int sellOrders_listView = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int sellPrice = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int sellText = 2131165198;
			
			// aapt resource value: 0x7f070020
			public const int settings_apiKeyButton = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int settings_apiKeyTextView = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int settings_inputText = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int settings_secretKeyButton = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int settings_secretKeyTextView = 2131165219;
			
			// aapt resource value: 0x7f070019
			public const int toolbar = 2131165209;
			
			// aapt resource value: 0x7f070009
			public const int totalBtcPrice = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int tradingPairText = 2131165185;
			
			// aapt resource value: 0x7f070027
			public const int yourOrder_amountRemaining = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int yourOrder_amountTotal = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int yourOrder_cancelButton = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int yourOrder_orderType = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int yourOrder_pricePerUnit = 2131165222;
			
			// aapt resource value: 0x7f070029
			public const int yourOrder_totalBtcPrice = 2131165225;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CurrencyLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CurrencyOrderListViewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomListFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int OrderConfirmationLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Settings_inputlayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int toolbar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int YourOrderListViewItem = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int top_menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_more_vert_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_refresh_black_24dp = 2130837505;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
